name: flutter_gank
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  #图标
  cupertino_icons: ^0.1.2
  #网络请求
  dio: ^1.0.0
  #Json序列化
  json_annotation: ^1.1.0
  #WebView
  flutter_webview_plugin: ^0.2.1+2
  #加载等待动画
  flutter_spinkit: ^2.0.1
  #图片加载、缓存
  cached_network_image: ^0.4.1+1
  #配置持久化
  shared_preferences: ^0.4.2
  #数据库
  sqflite: ^0.11.1
  #相册图片选择
  image_picker: ^0.4.6
  #标题栏搜索框
  flutter_search_bar: ^2.0.5
  #微信、QQ登录分享
  flutter_wechat: ^0.1.5
  flutter_qq: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

 #Json序列化
  build_runner: ^0.10.1
  json_serializable: ^1.1.0

  # For information on the generic Dart part of this file, see the
  # following page: https://www.dartlang.org/tools/pub/pubspec

  # The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - images/lake.jpg
    - images/gank.png
    - images/loading.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
